### ISSUE TITLE
[1.15.2] Mod does not load config files from defaultconfig

### ISSUE THREAD

**Issue by realTIMematrix** [MelanX/MoreVanillaTools#11]
Hi,

i'm using:

Minecraft: 1.15.2
Forge: 31.0.14
morevanillatools-1.15.2-1.3.3.jar

i recognized that your mod does not look into the defaultconfig folder to load an existing configuration. After it creates one in the config folder it is ok but for modpack developers it is quite handy to publish the toml files to the defaultconfig because then the logfile is not spammed with tons of lines full of creating stuff. 

So i found it really nice if the modmakers are creating files for the client and the server (saves) so that the logfile is not spammed.

**Comment by MelanX** [comment]
I see the problem. If the config is missing in configs dir it spams in the log.
I tried and it uses the defaultconfig for creating a new world. It just spams the stuff on first startup when creating the file for config dir. Because of that it's very low priority because everything works fine and is just spamming and not changing it for the config folder. 
The "problem" is that you need to change the config in saves/world anyway because it will never use the file in the normal config because of the new config system. This file is just as a "preview" or an "example" for a defaultconfig file.

**Comment by MelanX** [comment]
There would be a way to change the config in config but if I would use this the server and the client need to have the exactly same config. If only one value was different you couldn't join the server. That would be the "common" config. And that's a way I don't want to use. (just wanted you to know, it's not an option how to solve this problem here :D )

**Comment by MelanX** [comment]
Config is removed in 2.0
