### ISSUE TITLE
Sort branch 1.15.2 on GitHub

### ISSUE THREAD

**Issue by TheDirectorX** [MelanX/MoreVanillaTools#14]
**Branches** `1.15.2` and `1.14.2` differ (for example, **localization files** are in different places)
And I don't quite understand what **Language Data Generator** is for. https://github.com/MelanX/MoreVanillaTools/blob/1.15.x/src/main/java/de/melanx/MoreVanillaTools/util/data/Languages.java

**Comment by MelanX** [comment]
It’s because I switched to using data generators in 1.15.2. Everything in generated/ is auto generated by Java code. The LanguageDataGenerator is for generating the lang files. For English it’s very easy. For German it was a bit tricky because I need to translate the materials and the tool types. It’s a bit of more effort (because of that it’s balanced Kappa) but it’s worth it! If I'll ever change one little thing or add a new material, I just need to add a translation in my lib mod and it generates everything. It generates the lang stuff, it generates the recipes, it generates the item models. 
Because of that I will not accept jsons for 1.15+ as translation. You need to write your own class for generating the ru_ru.json. Because I like that you try to contribute this project, I have an idea: you give me the translations for the materials and the translations for the tools. I will but it all together that it can generate the names :)

If everything is clear, you can close this issue. If you still have questions, feel free to ask! I'll try to answer as good as I can :)

**Comment by MelanX** [comment]
Okay I looked at the given ru_ru.json and I could use everything from that. I just noticed that there is the ending ый for sword and axe and for everything else it’s ая. Only for Ender tools it’s different. If you could send me an alternative translation which fits to the other ending stuff it would be really cool and much more easy to code! And when you delete the other entries in your PR, you could also rename the the Ender tools :) if there is no alternative, let me know and I will code it with a bit more effort, that’s no problem.
Because of that you don’t need to send me the translation of each tool and material :D

**Comment by TheDirectorX** [comment]
Will it be convenient if someone wants to make another translation into another language?

And I don 't understand the folder structure on GitHub. This is more convenient when it is the same as in the original `.jar` file. And because of the data generator in `1.15.2`, the files are located in different places.

**For comparison:**
![image](https://user-images.githubusercontent.com/43481085/77154147-f54bc180-6abc-11ea-8fef-cc675b644257.png)
![image](https://user-images.githubusercontent.com/43481085/77154210-16acad80-6abd-11ea-9782-213d6ab97e69.png)

**Comment by MelanX** [comment]
If anyone would create a (e.g.) ru_ru.json in the generated folder, it will be deleted when I'm generating new data. 

Yes, it's in completely different directories. It's  a bit weird but that's how it works :) I could change the directory but in my opinion it's better this way for a better overview while coding.

**Comment by TheDirectorX** [comment]
> If anyone would create a (e.g.) ru_ru.json in the generated folder, it will be deleted when I'm generating new data.

This is useful information, you need to write a note somewhere for translators or refer to this answer if someone has a similar question.
